<a href="https://colab.research.google.com/github/AhmetA75/TASK7_ABCDEF/blob/main/TASK7_ABCDEF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np
from sklearn.preprocessing import Normalizer

In [2]:
df = pd.read_excel('Temporary_data3_Left_Right_Copy.xlsx')
df.head(10)

SEX  EDUC  MARISTAT  INDEPEND  RESIDENC  NACCFAM  ANYMEDS  SMOKYRS  \
0    2    18         1         1         1        1        1        0   
1    1    11         1         1         1        1        1        0   
2    2    16         1         1         1        1        1       10   
3    1    14         1         1         1        0        1        0   
4    1    16         1         1         2        0        1       50   
5    1    12         6         1         1        1        1       20   
6    1    16         1         1         1        1        1        0   
7    2    18         1         2         1        0        1        0   
8    2    16         1         1         1        1        1       20   
9    2    18         1         1         1        0        1        0   

   NACCTBI  DIABETES  ...   RSUPFR  RSUPFRM  RSUPPAR  RSUPPARM  RSUPTEM  \
0        0         0  ...  27.9038   2.2157  10.3481    1.7014  13.4250   
1        0         0  ...  29.0600   2.6900   9.2500    1.6300  14.8800   
2        0         1  ...  33.0000   2.5400  13.6900    1.5600  16.2300   
3        0         1  ...  31.6800   2.4100   9.6400    1.4500  15.1100   
4        0         0  ...  28.0631   1.9501   9.1125    1.0427  13.3763   
5        0         0  ...  29.9600   2.7200  11.7000    1.5000  16.7300   
6        0         0  ...  24.6500   2.1400  11.0600    1.5400  11.3300   
7        0         0  ...  23.1000   2.3400  13.5100    1.6900  13.4900   
8        0         0  ...  23.6300   2.6200   9.7400    1.9000   9.6500   
9        0         0  ...  25.1637   2.3796  14.1306    1.6671  13.5698   

   RSUPTEMM  RSUPMAR  RSUPMARM  RTRTEM  RTRTEMM  
0    1.7419   9.8700    1.6792  0.8906   1.1947  
1    2.3000   7.2700    1.8900  1.3800   2.0300  
2    2.0700  10.1100    1.8400  1.0100   1.5000  
3    1.6400  10.3900    1.8300  0.7400   1.1000  
4    1.6270   7.5844    1.4595  0.6638   0.8527  
5    2.1500   8.8800    1.7800  0.6600   1.1000  
6    1.5600   7.8800    1.9100  0.5800   0.8800  
7    2.3700   9.5300    1.8700  0.8800   1.4600  
8    1.7800   9.3700    2.0400  0.6200   1.6500  
9    2.3649  10.4055    1.9661  0.8163   1.6182  

[10 rows x 186 columns]

TASK 7A

In [3]:
df["ALCOHOL"].value_counts()
df["DIABETES"].value_counts()
df["INDEPEND"].value_counts()

1    1013
2     263
3      69
4       9
Name: INDEPEND, dtype: int64

In [4]:
encoder = OneHotEncoder(handle_unknown='ignore')

In [5]:
encoded_df = pd.DataFrame(encoder.fit_transform(df[['INDEPEND']]).toarray())
encoded_df.head()

0    1    2    3
0  1.0  0.0  0.0  0.0
1  1.0  0.0  0.0  0.0
2  1.0  0.0  0.0  0.0
3  1.0  0.0  0.0  0.0
4  1.0  0.0  0.0  0.0

In [6]:
last_df = df.join(encoded_df)
last_df = last_df[[0, 1, 2, 3]]
last_df.columns = ["independ_1", "independ_2", "independ_3", "independ_4"]

In [ ]:
'''
With the one-hot encoding method, a value of 0 or 1 is assigned for the index in each row, instead of a selected categorical feature.
Different values of the selected feature are assigned to the columns, so it is easier to find which group a record belongs to according to the selected feature.
'''
last_df

independ_1  independ_2  independ_3  independ_4
0            1.0         0.0         0.0         0.0
1            1.0         0.0         0.0         0.0
2            1.0         0.0         0.0         0.0
3            1.0         0.0         0.0         0.0
4            1.0         0.0         0.0         0.0
...          ...         ...         ...         ...
1349         1.0         0.0         0.0         0.0
1350         0.0         1.0         0.0         0.0
1351         1.0         0.0         0.0         0.0
1352         1.0         0.0         0.0         0.0
1353         1.0         0.0         0.0         0.0

[1354 rows x 4 columns]

TASK 7B

In [ ]:
pivot_1 = pd.pivot_table(data=df, values='CDRGLOB', index=['INDEPEND', 'ANYMEDS'], columns=['SEX'], aggfunc=np.mean, fill_value=0)

In [ ]:
'''
Create pivot table to get relation between CDRGLOB and SEX feature.
Use INDEPEND and ANYMEDS columns to obtain multidimensional analysis.
Interpreting the result: while INDEPEND is 2 and ANYMEDS is 0 or 1, average CDRGLOB value is 1.50 (close to >> 2), if SEX is 1. We can understand that:
SEX is determinative feature.
'''
pivot_1

SEX                      1         2
INDEPEND ANYMEDS                    
1        0        0.347826  0.424242
         1        0.531915  0.323580
2        0        1.500000  1.400000
         1        1.503650  1.361345
3        0        3.000000  0.000000
         1        2.272727  2.171429
4        1        3.000000  2.500000

In [ ]:
pivot_2 = pd.pivot_table(data=df, values='CDRGLOB', index=['NACCFAM', 'INDEPEND', 'APA'], columns=['SEX'], aggfunc=np.mean, fill_value=0)

In [ ]:
'''
Use INDEPEND, NACCFAM, APA columns to obtain multidimensional analysis.
Interpreting the result: although NACCFAM and INDEPEND values vary in different conditions, the SEX feature caused CDRGLOB to have close results.
Same SEX feature values are similar in some cases.
'''
pivot_2

SEX                          1         2
NACCFAM INDEPEND APA                    
0       1        0    0.451128  0.328502
                 1    1.250000  0.909091
        2        0    1.458333  1.138889
                 1    1.500000  1.615385
        3        0    2.250000  2.187500
                 1    2.363636  2.000000
        4        0    3.000000  3.000000
                 1    0.000000  3.000000
1       1        0    0.427273  0.266304
                 1    1.133333  0.928571
        2        0    1.482143  1.377778
                 1    1.567568  1.500000
        3        0    2.000000  2.000000
                 1    2.333333  2.300000
        4        0    3.000000  2.000000
                 1    3.000000  0.000000

In [ ]:
pivot_3 = pd.pivot_table(data=df, values='CDRGLOB', index=['NACCFAM', 'INDEPEND', 'GRAYVOL'], columns=['SEX'], aggfunc=np.mean, fill_value=0)

In [ ]:
'''
GRAVYOL is non-categorical variable -> bottleneck problem, it should be normalized or not used in these type of problems.
'''
pivot_3

SEX                       1  2
NACCFAM INDEPEND GRAYVOL      
0       1        398.846  0  1
                 418.315  0  1
                 427.993  0  0
                 430.738  0  1
                 444.240  0  1
...                      .. ..
1       4        516.238  0  3
                 524.258  3  0
                 539.174  3  0
                 589.086  3  0
                 628.990  0  1

[1351 rows x 2 columns]

TASK 7C

In [ ]:
df_copy = df.copy(deep=True)

In [ ]:
numeric_column_names = df.loc[:, df.dtypes == float].columns

In [ ]:
'''
Numeric column values to normalized values respect to NACCBRNV column value.
'''
for column in numeric_column_names:
    x = df[column].to_numpy()
    df_copy[column] /= df["NACCBRNV"]

In [ ]:
df_copy

SEX  EDUC  MARISTAT  INDEPEND  RESIDENC  NACCFAM  ANYMEDS  SMOKYRS  \
0       2    18         1         1         1        1        1        0   
1       1    11         1         1         1        1        1        0   
2       2    16         1         1         1        1        1       10   
3       1    14         1         1         1        0        1        0   
4       1    16         1         1         2        0        1       50   
...   ...   ...       ...       ...       ...      ...      ...      ...   
1349    1    20         1         1         1        1        1        0   
1350    1    16         1         2         1        0        1        0   
1351    2    14         2         1         1        1        1        0   
1352    2    20         3         1         1        1        1       25   
1353    2    14         1         1         1        1        1       10   

      NACCTBI  DIABETES  ...    RSUPFR   RSUPFRM   RSUPPAR  RSUPPARM  \
0           0         0  ...  0.024938  0.001980  0.009248  0.001521   
1           0         0  ...  0.026235  0.002428  0.008351  0.001472   
2           0         1  ...  0.027783  0.002138  0.011526  0.001313   
3           0         1  ...  0.028404  0.002161  0.008643  0.001300   
4           0         0  ...  0.027655  0.001922  0.008980  0.001028   
...       ...       ...  ...       ...       ...       ...       ...   
1349        0         0  ...  0.021636  0.002325  0.009242  0.001903   
1350        0         0  ...  0.020792  0.001761  0.008730  0.001246   
1351        0         0  ...  0.022328  0.001985  0.011599  0.001432   
1352        0         0  ...  0.028350  0.002197  0.009785  0.001537   
1353        0         0  ...  0.022060  0.002418  0.009922  0.001766   

       RSUPTEM  RSUPTEMM   RSUPMAR  RSUPMARM    RTRTEM   RTRTEMM  
0     0.011998  0.001557  0.008821  0.001501  0.000796  0.001068  
1     0.013433  0.002076  0.006563  0.001706  0.001246  0.001833  
2     0.013664  0.001743  0.008512  0.001549  0.000850  0.001263  
3     0.013548  0.001470  0.009316  0.001641  0.000663  0.000986  
4     0.013182  0.001603  0.007474  0.001438  0.000654  0.000840  
...        ...       ...       ...       ...       ...       ...  
1349  0.012368  0.002527  0.008165  0.002067  0.000590  0.000900  
1350  0.009048  0.001596  0.008558  0.001718  0.000609  0.000666  
1351  0.011852  0.001863  0.008875  0.001629  0.001105  0.001489  
1352  0.012452  0.001899  0.010056  0.001935  0.001185  0.001375  
1353  0.014005  0.002207  0.009992  0.001866  0.000833  0.001655  

[1354 rows x 186 columns]

In [ ]:
df_copy_1 = df.copy(deep=True)

In [ ]:
'''
Numeric column values to normalized values respect to for each column values.
'''
for column in numeric_column_names:
    x = df[column].to_numpy()
    normalizer = Normalizer().fit([x])
    transformed_arr = normalizer.transform([x])
    df_copy_1[column] = pd.Series(transformed_arr.ravel())

In [ ]:
df_copy_1

SEX  EDUC  MARISTAT  INDEPEND  RESIDENC  NACCFAM  ANYMEDS  SMOKYRS  \
0       2    18         1         1         1        1        1        0   
1       1    11         1         1         1        1        1        0   
2       2    16         1         1         1        1        1       10   
3       1    14         1         1         1        0        1        0   
4       1    16         1         1         2        0        1       50   
...   ...   ...       ...       ...       ...      ...      ...      ...   
1349    1    20         1         1         1        1        1        0   
1350    1    16         1         2         1        0        1        0   
1351    2    14         2         1         1        1        1        0   
1352    2    20         3         1         1        1        1       25   
1353    2    14         1         1         1        1        1       10   

      NACCTBI  DIABETES  ...    RSUPFR   RSUPFRM   RSUPPAR  RSUPPARM  \
0           0         0  ...  0.031383  0.027190  0.027330  0.031626   
1           0         0  ...  0.032683  0.033011  0.024430  0.030299   
2           0         1  ...  0.037114  0.031170  0.036156  0.028998   
3           0         1  ...  0.035630  0.029575  0.025460  0.026953   
4           0         0  ...  0.031562  0.023931  0.024067  0.019382   
...       ...       ...  ...       ...       ...       ...       ...   
1349        0         0  ...  0.027767  0.032554  0.027852  0.040359   
1350        0         0  ...  0.027882  0.025762  0.027492  0.027613   
1351        0         0  ...  0.026824  0.026016  0.032723  0.028440   
1352        0         0  ...  0.035259  0.029820  0.028576  0.031600   
1353        0         0  ...  0.024732  0.029575  0.026120  0.032716   

       RSUPTEM  RSUPTEMM   RSUPMAR  RSUPMARM    RTRTEM   RTRTEMM  
0     0.027310  0.022014  0.031257  0.025651  0.028320  0.022901  
1     0.030270  0.029067  0.023023  0.028871  0.043883  0.038913  
2     0.033016  0.026160  0.032017  0.028107  0.032117  0.028753  
3     0.030738  0.020726  0.032904  0.027955  0.023531  0.021086  
4     0.027211  0.020562  0.024019  0.022295  0.021108  0.016345  
...        ...       ...       ...       ...       ...       ...  
1349  0.028709  0.036438  0.029507  0.036023  0.021417  0.019687  
1350  0.021946  0.024046  0.032313  0.031291  0.023108  0.015232  
1351  0.025754  0.025149  0.030022  0.026580  0.037523  0.030479  
1352  0.028012  0.026539  0.035215  0.032690  0.041657  0.029137  
1353  0.028399  0.027803  0.031542  0.028413  0.026393  0.031629  

[1354 rows x 186 columns]

TASK 7D

In [ ]:
'''Normalization is done with the column's own values'''
df_copy_1.corrwith(df_copy_1["CDRGLOB"]).sort_values(ascending=False)

CDRGLOB     1.000000
INDEPEND    0.693881
APA         0.448558
LLATVENT    0.414033
RLATVENT    0.406806
              ...   
RHIPPO     -0.424068
LHIPPO     -0.442185
LENTM      -0.453646
RENTM      -0.478207
NACCMMSE   -0.746660
Length: 186, dtype: float64

In [ ]:
'''Normalization is done with the NACCBRNV values'''
df_copy.corrwith(df_copy["CDRGLOB"]).sort_values(ascending=False)

CDRGLOB     1.000000
INDEPEND    0.693881
APA         0.448558
LLATVENT    0.443272
RLATVENT    0.435256
              ...   
RHIPPO     -0.372265
RENTM      -0.385800
LHIPPO     -0.390896
NACCMMSE   -0.746660
NACCBRNV         NaN
Length: 186, dtype: float64

TASK 7E

In [37]:
cdr= df['CDRGLOB']

formula1 = (df['INDEPEND'] + df['APA'] ) / df['NACCFAM']
formula2 = ( df['LLATVENT'] + df['RLATVENT'] ) / df['RHIPPO'] 
formula3 = (df['LHIPPO'] + df['NACCMMSE'] ) / df['HYPERCHO'] + df['RENTM']

data01 = pd.concat([formula1, formula2, formula3, cdr], axis=1, join ="outer")
data01.columns =['formula1', 'formula2', 'formula3', 'CDRGLOB']

data01.corr().iloc[-1:,:-1]

formula1  formula2  formula3
CDRGLOB   0.71016  0.492214 -0.613657

TASK 7F

In [39]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import GradientBoostingClassifier
from time import time

In [53]:
y = df['CDRGLOB']

X = df.loc[:, ["APA", "NACCMMSE", "INDEPEND",]]  

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

In [54]:
grad_boost = GradientBoostingClassifier()

In [55]:
grad_boost.fit(X=x_train, y=y_train)

GradientBoostingClassifier()

In [56]:
print(f'TEST ACC GB ==> {grad_boost.score(x_test, y_test)}')

TEST ACC GB ==> 0.7306273062730627


In [57]:
grad_boost_param = {
                    
                    'learning_rate': [0.1, 0.01],
                    'n_estimators': [10, 300],
                    'max_depth': [3, 50] }

In [63]:
grid_grad_boost_8 = GridSearchCV(GradientBoostingClassifier(), grad_boost_param, cv=8) #  algoihm fitted grid
start = time() # For working time and tested by cv=8
grid_grad_boost_8.fit(x_train, y_train)
print(f'TIME FOR CV=8 ==> {time() - start}')
print(f'BEST PARAMS FOR GRID GRAD BOOST CV = 8 ==> {grid_grad_boost_8.best_params_}')
print(f'TEST ACC GRID GRAD BOOST CV = 8 ==> {grid_grad_boost_8.score(x_test, y_test)}')

TIME FOR CV=5 ==> 101.67319250106812
BEST PARAMS FOR GRID GRAD BOOST CV = 5 ==> {'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 300}
TEST ACC GRID GRAD BOOST CV = 5 ==> 0.7343173431734318


As seen above i used hyper optimization parameters for model to get best score

In [60]:
from sklearn.metrics import accuracy_score  # for testing our optimized model's efficency

In [64]:
sample = grid_grad_boost_8
sample.fit(x_train,y_train)

GridSearchCV(cv=8, estimator=GradientBoostingClassifier(),
             param_grid={'learning_rate': [0.1, 0.01], 'max_depth': [3, 50],
                         'n_estimators': [10, 300]})

In [65]:
y_sample = sample.predict(x_test)                                                          
accuracy=(accuracy_score(y_test, y_sample))                        

a=pd.DataFrame([accuracy]);
b=a.max()

print('The Max Value:',b);

The Max Value: 0    0.734317
dtype: float64


In [83]:
from sklearn.metrics import classification_report , confusion_matrix

In [90]:
class_names = ['class 0', 'class 1', 'class 2' , 'class 3']

In [98]:
print(classification_report(y_sample, y_test, target_names=class_names))



              precision    recall  f1-score   support

     class 0       0.94      0.76      0.84       160
     class 1       0.57      0.71      0.63        79
     class 2       0.55      0.67      0.60        27
     class 3       0.40      0.80      0.53         5

    accuracy                           0.73       271
   macro avg       0.61      0.73      0.65       271
weighted avg       0.78      0.73      0.75       271



In [100]:
print(confusion_matrix(y_sample, y_test))

[[121  38   1   0]
 [  8  56  13   2]
 [  0   5  18   4]
 [  0   0   1   4]]
